name: 💡 Feature Request
description: Suggest a new feature for Claude Desktop + Notion integration
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: What would you like to see added or improved?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important to you or the community?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context or examples?
